[build]
  publish = "public"
  command = "(git submodule update --init --force --recursive --remote && cp -a htc-blog/static/blog-images static/ ||:) && npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/belarus"
  to = "https://eventornado.com/event/build-for-belarus"
