backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}}'
    update: 'Update {{collection}}'
    delete: 'Delete {{collection}}'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'supporters'
    label: 'Supporters'
    folder: 'src/content/supporters'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'supporters',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Link', name: 'link', widget: 'string', required: true }
      - {
          label: 'Image',
          name: 'image',
          widget: image,
          media_library: { config: { multiple: false } },
        }

  - name: 'sponsors'
    label: 'Sponsors'
    folder: 'src/content/sponsors'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'sponsors',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Link', name: 'link', widget: 'string', required: true }
      - {
          label: 'Image',
          name: 'image',
          widget: image,
          media_library: { config: { multiple: false } },
        }

  - name: 'person'
    label: 'Person'
    folder: 'src/content/persons'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'person',
        }

      - {
          label: 'Person ID',
          name: 'personId',
          widget: 'hidden',
          default: '{{uuid}}',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Surname', name: 'surname', widget: 'string', required: true }
      - { label: 'Role', name: 'role', widget: 'string', required: true }
      - {
          label: 'Photo',
          name: 'photo',
          widget: 'image',
          default: '/src/img/placeholders/placeholder-person.png',
          media_library: { config: { multiple: false } },
          required: false,
        }
      - {
          label: 'About',
          name: 'about',
          widget: 'text',
          required: false,
          default: '',
        }
      - {
          label: 'Linkedin',
          name: 'linkedin',
          widget: 'string',
          required: false,
          default: '',
        }
      - label: 'Label'
        name: 'label'
        widget: 'select'
        options:
          - { label: 'Mentor', value: 'mentor' }
          - { label: 'Track lead', value: 'track-lead' }
          - { label: 'Our People', value: 'our-people' }
      - {
          label: 'Tracklist',
          name: 'tracklist',
          widget: 'relation',
          collection: 'tracklists',
          searchFields: ['title'],
          valueField: 'title',
          required: false,
          default: '',
        }

  - name: 'tracklists'
    label: 'Tracklists'
    folder: 'src/content/tracklists'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'tracklists',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Twitter hashtag',
          name: 'hashtag',
          widget: 'string',
          required: true,
        }
      - { label: 'Page content', name: 'body', widget: 'markdown' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Key Mentor',
          name: 'keyMentor',
          widget: 'relation',
          collection: 'person',
          searchFields: ['surname', 'name'],
          displayFields: ['surname', 'name'],
          valueField: 'personId',
          required: false,
          default: '',
        }
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: image,
          required: true,
          media_library: { config: { multiple: false } },
          default: '/uploads/portrait-placeholder.png',
        }
      - {
          label: 'Track Logo',
          name: 'trackLogo',
          widget: 'image',
          default: '/src/img/placeholders/hero.png',
          media_library: { config: { multiple: false } },
          required: false,
        }
      - {
          label: 'Twitter Widget Code',
          hint: 'Copy the code from EmbedSocial',
          name: 'widgetCode',
          widget: 'string',
          required: false,
          default: '',
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: 'Event Date', name: eventDate, widget: string }
          - { label: Subheading, name: subheading, widget: string, default: '' }
          - {
              label: 'Hero image',
              name: 'heroImage',
              widget: 'image',
              default: '/src/img/placeholders/hero.png',
              media_library: { config: { multiple: false } },
              required: false,
            }
          - {
              label: 'How it works',
              name: howItWorksDescription,
              widget: 'text',
              default: '',
            }
          - {
              label: 'Tracklist',
              name: tracklistDescription,
              widget: 'text',
              default: '',
            }
          - {
              label: 'Track Leads',
              name: trackleadsDescription,
              widget: 'text',
              default: '',
            }
          - {
              label: 'Timeline',
              name: timelineDescription,
              widget: 'text',
              default: '',
            }

          - {
              label: Timeline,
              name: timeline,
              widget: list,
              fields:
                [
                  {
                    label: 'Title',
                    name: 'title',
                    widget: 'string',
                    required: false,
                    default: '',
                  },
                  {
                    label: 'Is Active?',
                    name: 'isActive',
                    widget: 'boolean',
                    default: false,
                  },
                  {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    required: false,
                    default: '',
                  },
                  {
                    label: 'Date',
                    name: 'date',
                    widget: 'date',
                    required: false,
                    default: '',
                  },
                ],
            }
          - &contentItems {
              label: Content Items,
              name: contentItems,
              widget: list,
              fields:
                [
                  {
                    label: 'Title',
                    name: 'title',
                    widget: 'string',
                    required: false,
                    default: '',
                  },
                  {
                    label: 'Text content',
                    name: 'textContent',
                    widget: 'text',
                  },
                  {
                    label: 'Image',
                    name: 'image',
                    widget: 'image',
                    required: false,
                    default: '',
                  },
                  {
                    label: 'CTA text',
                    name: 'ctaText',
                    widget: 'string',
                    required: false,
                    default: '',
                  },
                  {
                    label: 'CTA link',
                    name: 'ctaLink',
                    widget: 'string',
                    required: false,
                    default: '',
                  },
                ],
            }
          - {
              label: 'How it works Items',
              name: howItWorksItems,
              widget: list,
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  {
                    label: 'Text content',
                    name: 'textContent',
                    widget: 'text',
                  },
                  { label: 'Image', name: 'image', widget: 'image' },
                  { label: 'CTA text', name: 'ctaText', widget: 'string' },
                  { label: 'CTA link', name: 'ctaLink', widget: 'string' },
                  {
                    label: 'Is enabled?',
                    name: 'isActive',
                    widget: 'boolean',
                    default: false,
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/faq/index.md'
        label: 'FAQ'
        name: 'faq'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'faq-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - *contentItems
      - file: 'src/pages/join/index.md'
        label: 'Join us'
        name: 'join'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'join-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: 'Our People Title', name: ourPeopleTitle, widget: string }
          - *contentItems
