backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          media_library: { config: { multiple: false } },
        }

  - name: 'supporters'
    label: 'Supporters'
    folder: 'src/pages/supporters'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'supporters',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Link', name: 'link', widget: 'string', required: true }
      - {
          label: 'Image',
          name: 'image',
          widget: image,
          media_library: { config: { multiple: false } },
        }

  - name: 'sponsors'
    label: 'Sponsors'
    folder: 'src/pages/sponsors'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'sponsors',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Link', name: 'link', widget: 'string', required: true }
      - {
          label: 'Image',
          name: 'image',
          widget: image,
          media_library: { config: { multiple: false } },
        }

  - name: 'person'
    label: 'Person'
    folder: 'src/content/persons'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'person',
        }
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Surname', name: 'surname', widget: 'string', required: true }
      - { label: 'Role', name: 'role', widget: 'string', required: true }
      - {
          label: 'Photo',
          name: 'photo',
          widget: 'image',
          default: '/uploads/portrait-placeholder.png',
          required: false,
        }
      - { label: 'About', name: 'about', widget: 'text', required: false }
      - {
          label: 'Linkedin',
          name: 'linkedin',
          widget: 'string',
          required: false,
        }
      - label: 'Label'
        name: 'label'
        widget: 'select'
        options:
          - { label: 'Mentor', value: 'mentor' }
          - { label: 'Track lead', value: 'track-lead' }
          - { label: 'Our People', value: 'our-people' }
      - {
          label: 'Tracklist',
          name: 'tracklist',
          widget: 'relation',
          collection: 'tracklists',
          searchFields: ['title'],
          valueField: 'title',
          required: false,
        }

  - name: 'tracklists'
    label: 'Tracklists'
    folder: 'src/content/tracklists'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'tracklists',
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Key Mentor',
          name: 'keyMentor',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Twitter hashtag',
          name: 'hashtag',
          widget: 'string',
          required: true,
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Key Mentor',
          name: 'keyMentor',
          widget: 'relation',
          collection: 'person',
          searchFields: ['title'],
          valueField: 'title',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: image,
          required: true,
          default: '/uploads/portrait-placeholder.png',
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - {
              label: 'Event Date',
              name: eventDate,
              widget: string,
              default: '3-5 april',
            }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/products/index.md'
        label: 'Products Page'
        name: 'products'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'product-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
